### ISSUE TITLE
V12 Avaliability

### ISSUE THREAD

**Issue by Caius1987** [RemyAllegro/CBR-PNK-CSB#1]
I wonder if will be there a v12 available any time.
Thanks

**Comment by RemyAllegro** [comment]
I've only tested up to the release version of CSB, which only supports v11. When CSB updates with v12 support I can then migrate the system over.

**Comment by Caius1987** [comment]
Ahhh great. They released a couple of days ago the 4.0 v12 beta version.
It could be any time now with the finished version.  =]
Thank you for your reply.

**Comment by Caius1987** [comment]
I'm sorry for being annoying.
But in case you are not aware CBS has updated to 4.0 =D

**Comment by RemyAllegro** [comment]
Just tested it, everything seems to be working with V12!
